### ISSUE TITLE
C7, 470uF is a little tall when the programmer board is stacked on top of the video board.

### ISSUE THREAD

**Issue by dennowiggle** [Z80-Retro/2068-Z80-TMS9118#2]
I just finished building the video board and stacked the programmer board on top and one of the leads of C3 on bottom side of the programmer board is pretty close to the top of the 470uF C7 capacitor on the video board.

It could just be my soldering and the 0.5mm taller alternate part I used  but it might be worth asking others to check their boards and provide feedback. Digikey description showed the alternate part and spec'd part as having the same installed seated height of 13mm. 
 
I improved the situation by custom designing M2.5 hex standoffs and 3D printing them so the distance between the boards was 14.2mm (13mm standoff + 1.2mm for screw head). I got inspiration from your video for that! Thanks, as I learned a new skill by making those.

A simpler solution would be replace it with a shorter cap such as a 9mm one with very similar specs such as Digikey 1189-2189-ND
- 470 µF 16 V Aluminum Electrolytic Capacitors Radial, Can, 2000 Hrs @ 105°C
- 8mm diameter x 9mm tall (10.5mm seated)
- Digikey part number 1189-2189-ND
- Rubycon 16WXA470MEFC8X9  
- https://www.digikey.com/en/products/detail/rubycon/16WXA470MEFC8X9/3563252
- I have not tested this alternate.

At minimum, a warning note should probably be added to the schematic to visually check the distance before powering on.

I will power on later this week and start having fun :). Thanks for the shout-out on the latest video - it encouraged me to add another.

**Comment by dennowiggle** [comment]
Another option:

On the programming board replace the 2x20 header with the one from Amazon used on the VDP. It increases the separation between the programming board and VDP board.

**Comment by johnwinans** [comment]
good ideas.  I am ordering a sample of this part.
This particular cap is a nominal filter cap that I thought improved things when I was testing on a solderless breadboard.  I suspect it meant more when running on the breadboard (long power supply wires etc.)  But it probably remains a good idea on the VDP board.

**Comment by johnwinans** [comment]
I fixed this with a BOM update.
